kind = "web"
previewPath = "/"
title = "Gameasu ERP"
version = "1.0.0"
id = "artifacts/edole-admin"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25655

[services.development]
run = "pnpm --filter @workspace/edole-admin run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/edole-admin", "run", "build" ]
publicDir = "artifacts/edole-admin/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25655"
BASE_PATH = "/"
