// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/gameasu-branding/ChaleurAfricaine.tsx": () => import("../components/mockups/gameasu-branding/ChaleurAfricaine.tsx"),
  "./components/mockups/gameasu-branding/EquipeProximite.tsx": () => import("../components/mockups/gameasu-branding/EquipeProximite.tsx"),
  "./components/mockups/gameasu-branding/PontGlobal.tsx": () => import("../components/mockups/gameasu-branding/PontGlobal.tsx"),
  "./components/mockups/controle-fiscal/DetailDeclaration.tsx": () => import("../components/mockups/controle-fiscal/DetailDeclaration.tsx"),
  "./components/mockups/controle-fiscal/ListeDeclarations.tsx": () => import("../components/mockups/controle-fiscal/ListeDeclarations.tsx")
};
